network:
  version: 2
  ethernets:
    enwild:
      match:
        name: en*
      addresses:
        - 192.168.1.40/24
      dhcp4: false
      gateway4: 192.168.1.1
      nameservers:
        addresses:
          - 192.168.1.1